import type { CourseModule } from './types.ts'

const PY = 'https://education.yandex.ru/handbook/python/article/'
const AL = 'https://education.yandex.ru/handbook/algorithms/article/'

export const PARTS = [
  { id: 'start', title: 'Старт', hint: 'Как устроен отбор и как пользоваться курсом' },
  { id: 'python', title: 'Python с нуля', hint: 'Язык на уровне, достаточном для контеста и собеседования' },
  { id: 'algo', title: 'Алгоритмы и структуры данных', hint: 'Главный фильтр и контеста, и технических секций' },
  { id: 'interview', title: 'Собеседование', hint: 'Как решать задачу вслух, без запуска кода, и что спрашивают' },
  { id: 'theory', title: 'Теория для секций', hint: 'Python изнутри, сети, базы данных, ОС — вопросы по теории' },
] as const

export const modules: CourseModule[] = [
  {
    id: 'start',
    title: 'Как устроен Intern week offer',
    part: 'start',
    goal: 'Понять этапы, сроки и критерии оценки, чтобы готовиться к тому, что реально проверяют.',
    stage: 'both',
    weight: 3,
    problems: [],
    coderunTags: [],
  },
  {
    id: 'py-basics',
    title: 'Python: основы',
    part: 'python',
    goal: 'Писать простые программы: ввод, вывод, вычисления, условия, циклы, строки.',
    stage: 'both',
    weight: 3,
    problems: [],
    coderunTags: ['implementation'],
    handbook: [
      { title: 'Хендбук Python: ввод, вывод, числа и строки', url: PY + 'vvod-i-vyvod-dannykh-operatsii-s-chislami-strokami-formatirovaniye' },
      { title: 'Хендбук Python: условный оператор', url: PY + 'uslovnyy-operator' },
      { title: 'Хендбук Python: циклы', url: PY + 'cikly' },
      { title: 'Хендбук Python: вложенные циклы', url: PY + 'vlozhennye-cikly' },
    ],
  },
  {
    id: 'py-collections',
    title: 'Python: коллекции и функции',
    part: 'python',
    goal: 'Уверенно работать со списками, словарями, множествами, кортежами и функциями и знать сложность их операций.',
    stage: 'both',
    weight: 3,
    problems: [],
    coderunTags: ['hash table', 'set'],
    handbook: [
      { title: 'Хендбук Python: строки, кортежи, списки', url: PY + 'stroki-kortezhi-spiski' },
      { title: 'Хендбук Python: множества и словари', url: PY + 'mnozhestva-slovari' },
      { title: 'Хендбук Python: списочные выражения и модель памяти', url: PY + 'spisochnye-vyrazheniya-model-pamyati-dlya-tipov-yazyka-python' },
      { title: 'Хендбук Python: функции и области видимости', url: PY + 'funkcii-oblasti-vidimosti-peredacha-parametrov-v-funkcii' },
      { title: 'Хендбук Python: аргументы и лямбда-функции', url: PY + 'pozicionnye-i-imenovannye-argumenty-funkcii-vysshih-poryadkov-lyambda-funkcii' },
    ],
  },
  {
    id: 'py-contest',
    title: 'Python для контеста',
    part: 'python',
    goal: 'Быстрый ввод-вывод, стандартная библиотека, вердикты проверяющей системы, стратегия на пять часов.',
    stage: 'contest',
    weight: 3,
    problems: [],
    coderunTags: ['implementation', 'parsing'],
    handbook: [
      { title: 'Хендбук Python: встроенные возможности для коллекций', url: PY + 'vstroennye-vozmozhnosti-po-rabote-s-kollekciyami' },
      { title: 'Хендбук алгоритмов: как работать с системой проверки', url: AL + 'algo-kak-rabotat-s-sistemoi-proverki-zadanii' },
    ],
  },
  {
    id: 'complexity',
    title: 'Сложность алгоритмов',
    part: 'algo',
    goal: 'Оценивать время и память решения и по ограничениям понимать, какая асимптотика нужна.',
    stage: 'both',
    weight: 3,
    problems: [],
    coderunTags: [],
    handbook: [{ title: 'Хендбук алгоритмов: алгоритмы и сложность', url: AL + 'algoritmy-i-slozhnost' }],
  },
  {
    id: 'arrays',
    title: 'Массивы и два указателя',
    part: 'algo',
    goal: 'Один проход с состоянием, серии, слияние, встречные и однонаправленные указатели.',
    stage: 'both',
    weight: 3,
    problems: ['monotonic', 'move-zeroes', 'remove-duplicates', 'merge-sorted', 'rle', 'ranges-compress', 'two-sum-sorted', 'valid-palindrome', 'cinema-seat', 'rotate-array', 'max-water', 'three-sum'],
    coderunTags: ['two pointers'],
    handbook: [{ title: 'Хендбук алгоритмов: задача «Максимальное произведение»', url: AL + 'zadacha-maksimalnoe-proizvedenie' }],
  },
  {
    id: 'hashing',
    title: 'Хеш-таблицы: словари и множества',
    part: 'algo',
    goal: 'Подсчёт частот, группировка, поиск пары, префиксные суммы со словарём.',
    stage: 'both',
    weight: 3,
    problems: ['two-sum', 'valid-anagram', 'first-unique', 'group-anagrams', 'longest-consecutive', 'subarray-sum-k'],
    coderunTags: ['hash table', 'set', 'hashing'],
    handbook: [
      { title: 'Хендбук алгоритмов: словарь', url: AL + 'slovar' },
      { title: 'Хендбук алгоритмов: множество', url: AL + 'mnozhestvo' },
    ],
  },
  {
    id: 'sorting',
    title: 'Сортировки и события',
    part: 'algo',
    goal: 'Как устроены сортировки, сортировка с ключом, отрезки и метод событий.',
    stage: 'both',
    weight: 3,
    problems: ['can-attend', 'merge-intervals', 'sort-colors', 'largest-number'],
    coderunTags: ['sorting', 'sweep line'],
    handbook: [
      { title: 'Хендбук алгоритмов: разделяй и властвуй', url: AL + 'razdelyaj-i-vlastvuj' },
      { title: 'Хендбук алгоритмов: модификация быстрой сортировки', url: AL + 'modifikaciya-bystroj-sortirovki' },
      { title: 'Хендбук алгоритмов: подсчёт инверсий', url: AL + 'podschet-inversij' },
    ],
  },
  {
    id: 'greedy',
    title: 'Жадные алгоритмы',
    part: 'algo',
    goal: 'Узнавать задачи, где локально лучший выбор ведёт к ответу, и уметь это обосновать.',
    stage: 'contest',
    weight: 2,
    problems: [],
    coderunTags: ['greedy'],
    handbook: [
      { title: 'Хендбук алгоритмов: жадные алгоритмы', url: AL + 'zhadnye-algoritmy' },
      { title: 'Хендбук алгоритмов: задача «Максимальный оклад»', url: AL + 'zadacha-maksimalnyj-oklad' },
      { title: 'Хендбук алгоритмов: задача «Сбор подписей»', url: AL + 'zadacha-sbor-podpisej' },
    ],
  },
  {
    id: 'binsearch',
    title: 'Бинарный поиск',
    part: 'algo',
    goal: 'Левый и правый бинпоиск без ошибок на единицу, бинпоиск по ответу и по вещественным числам.',
    stage: 'both',
    weight: 3,
    problems: ['binary-search', 'int-sqrt', 'first-last', 'search-rotated', 'koko-bananas', 'ship-capacity'],
    coderunTags: ['binary search'],
    handbook: [{ title: 'Хендбук алгоритмов: двоичный поиск', url: AL + 'dvoichnyj-poisk' }],
  },
  {
    id: 'prefix-window',
    title: 'Префиксные суммы и скользящее окно',
    part: 'algo',
    goal: 'Суммы на отрезках за O(1), разностный массив, окна фиксированной и переменной длины.',
    stage: 'both',
    weight: 3,
    problems: ['range-sum', 'max-avg-window', 'longest-unique-substring', 'max-ones-k-flips', 'min-window'],
    coderunTags: ['prefix sum', 'sliding window'],
  },
  {
    id: 'stack-queue',
    title: 'Стек, очередь, дек',
    part: 'algo',
    goal: 'Скобки, выражения, монотонный стек, минимум в окне, моделирование очередей.',
    stage: 'both',
    weight: 3,
    problems: ['valid-parentheses', 'min-stack', 'eval-rpn', 'simplify-path', 'daily-temperatures', 'sliding-max'],
    coderunTags: ['stack', 'queue', 'deque'],
    handbook: [
      { title: 'Хендбук алгоритмов: стек', url: AL + 'stek' },
      { title: 'Хендбук алгоритмов: дек', url: AL + 'dek-' },
    ],
  },
  {
    id: 'linked',
    title: 'Связные списки',
    part: 'algo',
    goal: 'Разворот, слияние, быстрый и медленный указатели — классика устных секций.',
    stage: 'interview',
    weight: 2,
    problems: ['cycle-start'],
    coderunTags: [],
    handbook: [{ title: 'Хендбук алгоритмов: односвязный список', url: AL + 'odnosvyaznyj-spisok' }],
  },
  {
    id: 'recursion',
    title: 'Рекурсия и перебор',
    part: 'algo',
    goal: 'Писать рекурсию без утечек состояния, генерировать скобки, перестановки, подмножества.',
    stage: 'both',
    weight: 2,
    problems: ['generate-parentheses', 'subsets', 'permutations', 'combination-sum', 'letter-combinations'],
    coderunTags: ['backtracking', 'brute force'],
    handbook: [
      { title: 'Хендбук алгоритмов: рекурсивные алгоритмы', url: AL + 'rekursivnye-algoritmy' },
      { title: 'Хендбук алгоритмов: полный перебор и его оптимизация', url: AL + 'polnyj-perebor-i-optimizaciya-perebora' },
    ],
  },
  {
    id: 'trees',
    title: 'Деревья',
    part: 'algo',
    goal: 'Обходы, рекурсия по дереву, дерево поиска, префиксное дерево, деревья в формате контеста.',
    stage: 'both',
    weight: 2,
    problems: ['max-depth', 'invert-tree', 'valid-bst', 'level-order', 'lca-bst', 'diameter'],
    coderunTags: ['tree', 'trie'],
  },
  {
    id: 'graphs',
    title: 'Графы',
    part: 'algo',
    goal: 'DFS, BFS, компоненты, циклы, топологическая сортировка, Дейкстра, DSU.',
    stage: 'both',
    weight: 2,
    problems: ['num-islands', 'count-components', 'shortest-path-grid', 'course-schedule', 'network-delay'],
    coderunTags: ['bfs', 'dfs', 'graph theory', 'topological sort', 'shortest paths', 'union-find'],
    handbook: [
      { title: 'Хендбук алгоритмов: природа графа', url: AL + 'priroda-grafa' },
      { title: 'Хендбук алгоритмов: представление графа в памяти', url: AL + 'predstavlenie-grafa-v-pamyati-kompyutera' },
      { title: 'Хендбук алгоритмов: обходы графа', url: AL + 'obhody-grafa' },
      { title: 'Хендбук алгоритмов: компоненты связности', url: AL + 'algoritm-nahozhdeniya-komponent-svyaznosti-v-grafe' },
      { title: 'Хендбук алгоритмов: кратчайший путь', url: AL + 'zadacha-poiska-kratchajshego-puti-v-grafe' },
    ],
  },
  {
    id: 'heap',
    title: 'Куча и очередь с приоритетом',
    part: 'algo',
    goal: 'heapq, k лучших, слияние k списков, медиана потока, расписания.',
    stage: 'both',
    weight: 2,
    problems: ['kth-largest', 'top-k-frequent', 'meeting-rooms-ii', 'merge-k-sorted', 'median-stream'],
    coderunTags: ['heap'],
    handbook: [{ title: 'Хендбук алгоритмов: очередь с приоритетом', url: AL + 'ochered-s-prioritetom' }],
  },
  {
    id: 'dp',
    title: 'Динамическое программирование',
    part: 'algo',
    goal: 'От рекурсии к таблице: одномерная и двумерная динамика, рюкзак, НВП, НОП, восстановление ответа.',
    stage: 'contest',
    weight: 2,
    problems: ['climb-stairs', 'max-subarray', 'house-robber', 'coin-change', 'unique-paths', 'lis', 'lcs', 'knapsack', 'edit-distance'],
    coderunTags: ['dynamic programming', 'dp on sequences', 'dp on grids'],
    handbook: [
      { title: 'Хендбук алгоритмов: динамическое программирование', url: AL + 'dinamicheskoe-programmirovanie' },
      { title: 'Хендбук алгоритмов: задача о рюкзаке', url: AL + 'zadacha-o-ryukzake' },
      { title: 'Хендбук алгоритмов: расстояние редактирования', url: AL + 'zadacha-rasstoyanie-redaktirovaniya' },
      { title: 'Хендбук алгоритмов: наибольшая общая подпоследовательность', url: AL + 'zadacha-lcs' },
    ],
  },
  {
    id: 'math',
    title: 'Математика для контеста',
    part: 'algo',
    goal: 'Делимость, НОД, простые числа, остатки, биты, комбинаторика, немного геометрии.',
    stage: 'contest',
    weight: 2,
    problems: ['power-of-two'],
    coderunTags: ['math', 'number theory', 'combinatorics', 'bit manipulation', 'geometry', 'probability theory'],
    handbook: [{ title: 'Хендбук алгоритмов: НОД и НОК', url: AL + 'vychislenie-nok-i-nod' }],
  },
  {
    id: 'strings',
    title: 'Строки и разбор данных',
    part: 'algo',
    goal: 'Строки в Python и стоимость операций, палиндромы, анаграммы, окна на строках, хеширование, разбор логов, JSON и CSV.',
    stage: 'both',
    weight: 2,
    problems: ['valid-palindrome', 'rle', 'group-anagrams', 'min-window'],
    coderunTags: ['strings', 'string matching', 'parsing', 'json'],
  },
  {
    id: 'primitives',
    title: 'Примитивы: кэши, счётчики, итераторы',
    part: 'algo',
    goal: 'Спроектировать класс с нужной сложностью операций: LRU-кэш, счётчик запросов, итераторы.',
    stage: 'interview',
    weight: 2,
    problems: ['lru-cache', 'min-stack'],
    coderunTags: [],
  },
  {
    id: 'interview',
    title: 'Как пройти техническую секцию',
    part: 'interview',
    goal: 'Алгоритм действий на секции, код без запуска, типичные ошибки, встречи с командами.',
    stage: 'interview',
    weight: 3,
    problems: [],
    coderunTags: [],
  },
  {
    id: 'py-deep',
    title: 'Python изнутри',
    part: 'theory',
    goal: 'Ответить на теоретические вопросы по языку: объекты, память, замыкания, генераторы, ООП, GIL, asyncio.',
    stage: 'interview',
    weight: 3,
    problems: [],
    coderunTags: [],
    handbook: [
      { title: 'Хендбук Python: рекурсия, декораторы, генераторы', url: PY + 'rekursiya-dekoratory-generatory' },
      { title: 'Хендбук Python: объектная модель', url: PY + 'obuektnaya-model-python-klassy-polya-i-metody' },
      { title: 'Хендбук Python: волшебные методы и наследование', url: PY + 'volshebnye-metody-pereopredelenie-metodov-nasledovanie' },
      { title: 'Хендбук Python: исключения и модули', url: PY + 'model-isklyuchenij-python-try-except-else-finally-moduli' },
    ],
  },
  {
    id: 'backend',
    title: 'Бэкенд: сети, базы данных, ОС',
    part: 'theory',
    goal: 'Базовая теория, которую спрашивают у бэкенд-стажёра: HTTP, TCP, SQL, индексы, транзакции, процессы.',
    stage: 'interview',
    weight: 2,
    problems: [],
    coderunTags: ['http'],
    handbook: [
      { title: 'Хендбук Python: разработка бэкенда банковского приложения', url: PY + 'razrabotka-bekenda-bankovskogo-prilozheniia' },
      { title: 'Хендбук Python: создание ASGI/WSGI-сервера', url: PY + 'sozdanie-asgiwsgi-servera' },
    ],
  },
]

export const moduleById = Object.fromEntries(modules.map((m) => [m.id, m]))
